---
{{- if eq .Values.kubernetesType "Openshift" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Namespace }}-role
rules:
- apiGroups:
  - security.openshift.io
{{- if .Values.securityContext.privileged  }}
  resourceNames:
  - privileged
{{- else }}
  resourceNames:
  - anyuid
{{- end }}
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Namespace }}-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Chart.Name }}-{{ .Release.Namespace }}-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Namespace }}-imagepull-binding
  namespace: oaicicd-core
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: "system:image-puller"
  apiGroup: rbac.authorization.k8s.io
{{- end }}
